name: ffms
description: Fast Food Management System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  postgres: ^2.6.3
  provider: ^6.1.1
  fl_chart: ^0.65.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  pdf: ^3.10.7
  printing: ^5.11.1
  flutter_secure_storage: ^9.0.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700